version: "3"
services:
  work:
    image: composer
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  web:
    build: .
    command: php artisan serve --host 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    working_dir: /myapp
    depends_on:
      - db
